-define(COMMANDS,
        [{server_info, 0},
         {active_tasks, 1},
         {all_dbs, 2},
         {config, 3},
         {config_section, 4},
         {config_section_key, 5},
         {db_updates, 6},
         {log, 7},
         {replicate, 8},
         {restart, 9},
         {stats, 10},
         {uuids, 11},
         {db_exists, 12},
         {db_info, 13},
         {create_db, 14},
         {delete_db, 15}]).
