%% [{CommandCode, CommandName, {Module, Function}}]
-define(COMMANDS,
        [
         {0,  get_version,        {couch_server, get_version}},
         {1,  active_tasks,       {}},
         {2,  all_dbs,            {couch_server, all_databases}},
         {3,  config,             {couch_config, all}},
         {4,  config_section,     {couch_config, get}},
         {5,  config_section_key, {couch_config, get}},
         {6,  db_updates,         {}},
         {7,  log,                {}},
         {8,  replicate,          {}},
         {9,  restart,            {}},
         {10, stats,              {}},
         {11, uuids,              {}},
         {12, db_exists,          {}},
         {13, db_info,            {}},
         {14, create_db,          {}},
         {15, delete_db,          {}},
         {16, all_docs,           {}},
         {17, bulk_docs,          {}},
         {18, db_changes,         {}},
         {19, db_compact,         {}},
         {20, db_compact_ddoc,    {}},
         {21, ddoc_info,          {}},
         {22, ddoc,               {}},
         {23, create_ddoc,        {}},
         {24, delete_ddoc,        {}},
         {25, copy_ddoc,          {}}
        ]).
